# Generated by Django 5.0 on 2023-12-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_productmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product_kit_Model',
        ),
    ]
